version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: music_campaigns
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d music_campaigns"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://backend_user:${DB_PASSWORD}@postgres:5432/music_campaigns
      FLASK_ENV: production
      FLASK_DEBUG: false
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
