version: '3.8'

services:
  backend:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: true
    volumes:
      - .:/app
    ports:
      - "5001:5001"
  
  postgres:
    ports:
      - "5432:5432"
