version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: music_postgres_prod
    environment:
      POSTGRES_DB: music_campaigns
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d music_campaigns"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - backend-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: music_backend_prod
    environment:
      DATABASE_URL: postgresql://backend_user:${DB_PASSWORD}@postgres:5432/music_campaigns
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_DEBUG: ${FLASK_DEBUG:-false}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    networks:
      - backend-network

  nginx:
    image: nginx:1.25-alpine
    container_name: music_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend-network

  # Optional: Cloudflare Tunnel (uncomment when ready)
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared_tunnel
  #   command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
  #   restart: unless-stopped
  #   depends_on:
  #     - nginx
  #   networks:
  #     - backend-network

volumes:
  postgres_prod_data:

networks:
  backend-network:
    driver: bridge
